"""Local Codex <-> Altium API bridge. No GUI input or binary-file editing.

Transport: standard MCP stdio, or the matching CLI for an already running chat.
Each job has its own DelphiScript project, log and result, so stale responses
cannot be mistaken for success. Source and runtime live in the engineering repo.
"""
from __future__ import annotations

import argparse
import asyncio
import ctypes
import configparser
import hashlib
import json
import logging
import os
from pathlib import Path
import shutil
import subprocess
import sys
import time
import threading
import uuid
from contextlib import contextmanager
from obstacle_policy import guard_action

BASE = Path(__file__).resolve().parent
CONFIG_PATH = BASE / 'bridge_config.json'
CONFIG = json.loads(CONFIG_PATH.read_text(encoding='utf-8-sig')) if CONFIG_PATH.exists() else {}
EXE = Path(os.environ.get('ALTIUM_EXE', CONFIG.get('altium_exe', r'Z:\Altium\X2.EXE')))
# Runtime is always inside this checkout, even if an old config specified state_dir.
STATE = BASE / 'runtime'
STATE.mkdir(parents=True, exist_ok=True)
_LOCK_STATE = threading.local()


def pas_string(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def desktop_available() -> bool:
    """Read input-desktop access; never switch or unlock a Windows desktop."""
    if os.name != "nt":
        return False
    user32 = ctypes.WinDLL("user32", use_last_error=True)
    user32.OpenInputDesktop.restype = ctypes.c_void_p
    user32.OpenInputDesktop.argtypes = [ctypes.c_uint, ctypes.c_bool, ctypes.c_uint]
    user32.CloseDesktop.argtypes = [ctypes.c_void_p]
    handle = user32.OpenInputDesktop(0, False, 1)  # DESKTOP_READOBJECTS
    if not handle:
        return False
    try:
        name = ctypes.create_unicode_buffer(256)
        needed = ctypes.c_uint()
        ok = user32.GetUserObjectInformationW(
            ctypes.c_void_p(handle), 2, name, ctypes.sizeof(name), ctypes.byref(needed)
        )
        return bool(ok and name.value.lower() == "default")
    finally:
        user32.CloseDesktop(handle)


@contextmanager
def operation_lock():
    """Serialize every bridge process, including CLI and MCP clients."""
    if getattr(_LOCK_STATE, 'held', False):
        yield
        return
    import msvcrt
    with (STATE / "operation.lock").open("a+b") as stream:
        stream.seek(0)
        if not stream.read(1):
            stream.write(b"0")
            stream.flush()
        stream.seek(0)
        try:
            msvcrt.locking(stream.fileno(), msvcrt.LK_NBLCK, 1)
        except OSError as exc:
            raise RuntimeError("Another Altium bridge operation is active") from exc
        try:
            _LOCK_STATE.held = True
            yield
        finally:
            _LOCK_STATE.held = False
            stream.seek(0)
            msvcrt.locking(stream.fileno(), msvcrt.LK_UNLCK, 1)


def _script_source(body: str, declarations: str, helpers: str, job: Path) -> str:
    return f"""// Generated by Codex Altium bridge. All coordinates are in mils.
var JobLog: TStringList;
procedure LogStep(S: String);
begin
  JobLog.Add(S);
  JobLog.SaveToFile({pas_string(str(job / 'steps.txt'))});
end;
{helpers}
procedure Run;
var
  ResultText: String;
  OutputLines: TStringList;
  {declarations}
begin
  JobLog := TStringList.Create;
  ResultText := '';
  LogStep('START');
  try
    {body}
    LogStep('FINISHED');
    OutputLines := TStringList.Create;
    OutputLines.Text := ResultText;
    OutputLines.SaveToFile({pas_string(str(job / 'result.txt'))});
    OutputLines.Free;
  finally
    JobLog.Free;
  end;
end;
"""


@guard_action
def run_script(body: str, declarations: str = "", helpers: str = "", timeout: int = 45, _recovery_probe: bool = False) -> dict:
    from job_diagnostics import preflight, diagnose
    hazards = preflight(body, declarations, helpers)
    if hazards:
        return {"success": False, "error": "SCRIPT_PREFLIGHT_REJECTED", "hazards": hazards,
                "message": "Correct the demonstrated API hazard before launching Altium; no CAD writes ran."}
    if not desktop_available():
        return {"success": False, "error": "WINDOWS_DESKTOP_UNAVAILABLE",
                "message": "Unlock Windows before running Altium commands."}
    if not EXE.is_file():
        return {"success": False, "error": "ALTIUM_EXE_MISSING", "path": str(EXE)}
    import psutil
    editors = []
    for proc in psutil.process_iter(['pid', 'name', 'exe']):
        try:
            if proc.info['name'].lower() == 'x2.exe' and proc.info['exe'].lower() == str(EXE).lower():
                command_line = ' '.join(proc.cmdline()).lower()
                if '-rscriptingSystem:runscript'.lower() in command_line and str(STATE / 'jobs').lower() in command_line:
                    continue  # our short-lived secondary launcher is not another editor
                editors.append(proc.info['pid'])
        except (AttributeError, psutil.Error):
            continue
    if not editors:
        return {"success": False, "error": "ALTIUM_NOT_RUNNING",
                "message": "Open Altium normally before live commands. The bridge does not create or terminate a primary editor."}
    if len(editors) > 1:
        return {"success": False, "error": "MULTIPLE_ALTIUM_EDITORS", "pids": editors,
                "message": "Save your documents and leave one Altium instance before native commands."}
    timeout = max(2, min(int(timeout), 60))
    with operation_lock():
        blocked = STATE / 'blocked-job.json'
        if blocked.exists() and not _recovery_probe:
            return {"success": False, "error": "EXECUTOR_RECOVERY_REQUIRED",
                    "blocked_job": json.loads(blocked.read_text(encoding='utf-8')),
                    "recovery": "Diagnose the previous job, inspect saved output, stop the failed script in Altium, then call altium_recover_executor. No automatic replay."}
        job = STATE / "jobs" / uuid.uuid4().hex
        job.mkdir(parents=True)
        module = "CodexJob_" + job.name[:12]
        unit = job / (module + ".pas")
        project = job / (module + ".PrjScr")
        unit.write_text(_script_source(body, declarations, helpers, job), encoding="utf-8")
        project.write_text(f"[Design]\nVersion=1.0\n[Document1]\nDocumentPath={module}.pas\n", encoding="ascii")
        (job / 'request.json').write_text(json.dumps({'body': body, 'declarations': declarations,
            'helpers': helpers, 'timeout': timeout, 'editor_pids': editors}, ensure_ascii=False, indent=2), encoding='utf-8')
        # Altium's custom -R parser needs the literal quoted subfields. Passing
        # an argv list causes Windows escaping to change their representation.
        # No shell is involved. All embedded paths are generated locally.
        command = (f'"{EXE}" -RScriptingSystem:RunScript('
                   f'ProjectName="{project}"|ProcName="{module}.pas>Run")')
        launcher = subprocess.Popen(command, shell=False)
        started = time.monotonic()
        result_file = job / "result.txt"
        while not result_file.is_file() and time.monotonic() - started < timeout:
            time.sleep(0.15)
        steps_file = job / "steps.txt"
        steps = steps_file.read_text(encoding="mbcs", errors="replace").splitlines() if steps_file.exists() else []
        success = result_file.exists() and bool(steps) and steps[-1] == "FINISHED"
        result = {"success": success, "job_dir": str(job), "steps": steps,
                  "elapsed_seconds": round(time.monotonic() - started, 2)}
        if success:
            content = result_file.read_text(encoding="mbcs", errors="replace").strip()
            try:
                result["result"] = json.loads(content)
            except json.JSONDecodeError:
                result["result"] = content
        else:
            result["error"] = "SCRIPT_FAILED_OR_BLOCKED"
            result["last_step"] = steps[-1] if steps else "NOT_STARTED"
            result["recovery"] = "Inspect the Altium error/debugger, stop the failed script, then retry. Do not blindly repeat a mutation."
            result['diagnosis'] = diagnose(job, any(psutil.pid_exists(pid) for pid in editors))
            blocked.write_text(json.dumps({'job_dir': str(job), 'diagnosis': result['diagnosis']}, ensure_ascii=False, indent=2), encoding='utf-8')
            # Only terminate the secondary launcher we created, never the
            # already running editor containing the user's design.
            if launcher.poll() is None:
                launcher.terminate()
        with (STATE / "operations.jsonl").open("a", encoding="utf-8") as stream:
            stream.write(json.dumps(result, ensure_ascii=False) + "\n")
        return result


@guard_action
def diagnose_job(job_dir: str) -> dict:
    from job_diagnostics import diagnose
    import psutil
    job = Path(job_dir).resolve()
    if job.parent != (STATE / 'jobs').resolve() or not job.is_dir():
        raise ValueError('Use the exact job_dir returned by this bridge')
    request = job / 'request.json'
    pids = json.loads(request.read_text(encoding='utf-8')).get('editor_pids', []) if request.exists() else []
    return diagnose(job, any(psutil.pid_exists(pid) for pid in pids) if pids else None)


@guard_action
def recover_executor() -> dict:
    """Probe only; never stops or kills the user's editor and never replays a write."""
    with operation_lock():
        result = run_script("ResultText := 'CODEX_RECOVERY_PROBE_OK';", timeout=5, _recovery_probe=True)
        if result.get('success') and result.get('result') == 'CODEX_RECOVERY_PROBE_OK':
            (STATE / 'blocked-job.json').unlink(missing_ok=True)
            result['executor_recovered'] = True
        else:
            result['executor_recovered'] = False
        return result


@guard_action
def status(live: bool = False) -> dict:
    info = {"altium_exe": str(EXE), "exe_exists": EXE.is_file(),
            "state_dir": str(STATE), "desktop_available": desktop_available(),
            "transport": "stdio", "bridge": "CodexAltium"}
    blocked = STATE / 'blocked-job.json'
    info['executor_blocked'] = blocked.exists()
    if blocked.exists():
        info['blocked_job'] = json.loads(blocked.read_text(encoding='utf-8'))
    if live:
        info["live_check"] = run_script("ResultText := 'CODEX_ALTIUM_LIVE_OK';")
    return info


def backup_document(path: str) -> str | None:
    source = Path(path).resolve()
    if not source.is_file():
        return None
    dest = STATE / "backups" / (time.strftime("%Y%m%d-%H%M%S") + "-" + uuid.uuid4().hex[:8]) / source.name
    dest.parent.mkdir(parents=True)
    shutil.copy2(source, dest)
    return str(dest)


@guard_action
def open_document(path: str) -> dict:
    target = Path(path).resolve()
    kinds = {".schdoc": "SCH", ".schlib": "SCHLIB", ".pcbdoc": "PCB", ".pcblib": "PCBLIB"}
    kind = kinds.get(target.suffix.lower())
    if not kind or not target.is_file():
        return {"success": False, "error": "Unsupported or missing document", "path": str(target)}
    return run_script(f"D := Client.OpenDocument({pas_string(kind)}, {pas_string(str(target))}); "
                      "if D <> Nil then begin Client.ShowDocument(D); ResultText := 'OPENED'; end else ResultText := 'OPEN_FAILED';",
                      "D: IServerDocument;")


@guard_action
def inspect_schematic(path: str) -> dict:
    from manifest import inspect_body
    return run_script(*inspect_body(str(Path(path).resolve())))


@guard_action
def create_schematic(manifest_path: str, output_path: str) -> dict:
    from manifest import build_sheet
    target = Path(output_path).resolve()
    if target.suffix.lower() != ".schdoc":
        raise ValueError("Output must have .SchDoc extension")
    if target.exists():
        raise ValueError("Creation refuses to replace an existing sheet; use a new filename")
    data = json.loads(Path(manifest_path).read_text(encoding="utf-8"))
    body, declarations, helpers = build_sheet(data, str(target))
    target.parent.mkdir(parents=True, exist_ok=True)
    result = run_script(body, declarations, helpers)
    result["file_exists"] = target.is_file()
    if target.is_file():
        result["sha256"] = hashlib.sha256(target.read_bytes()).hexdigest()
    result["success"] = result["success"] and result["file_exists"]
    return result


@guard_action
def set_component_parameter(path: str, designator: str, parameter: str, value: str) -> dict:
    from manifest import parameter_body
    saved_copy = backup_document(path)
    result = run_script(*parameter_body(str(Path(path).resolve()), designator, parameter, value))
    result["backup"] = saved_copy
    result["success"] = result["success"] and result.get("result") == "UPDATED"
    return result


@guard_action
def compile_project(path: str) -> dict:
    from project_api import compile_body
    target = Path(path).resolve()
    if not target.is_file() or target.suffix.lower() != '.prjpcb':
        raise ValueError('An existing .PrjPcb path is required')
    return run_script(*compile_body(str(target)))


def serve():
    from mcp.server.fastmcp import FastMCP
    server = FastMCP("CodexAltium", instructions=(
        "Use explicit absolute paths. Start with altium_status(live=True). "
        "Creation refuses to overwrite sheets. After edits inspect the saved document; "
        "a script success is not an ERC result. CAD scripts use mils. "
        "If desktop is unavailable ask the user to unlock it. Never bypass locks. "
        "PDF reconstruction is a draft until pin-net and ERC checks pass. "
        "Do not invoke GUI or shell automation through scripts. "
        "Repair code/input failures autonomously. For external or ambiguous constraints report evidence and uncertainty; "
        "ask for a choice only when human action or a new strategy is required. "
        "Stop after three attempts without new evidence or ten minutes without progress. Never replay ambiguous CAD writes."))

    @server.tool()
    @guard_action
    def altium_read_saved_schematic(path: str) -> dict:
        """Read saved native binary SchDoc without Altium: components, pins, wires, and inferred nets. Does not include unsaved edits; inferred nets are not compiler/ ERC results."""
        from eda_agent.fileio import (read_schematic_components, read_schematic_pins,
                                     read_schematic_wires, read_schematic_nets)
        target = Path(path).resolve()
        if not target.is_file() or target.suffix.lower() != '.schdoc':
            raise ValueError('An existing .SchDoc path is required')
        return {'path': str(target), 'sha256': hashlib.sha256(target.read_bytes()).hexdigest(),
                'source': 'saved_disk_file', 'components': read_schematic_components(target),
                'pins': read_schematic_pins(target), 'wires': read_schematic_wires(target),
                'inferred_nets': read_schematic_nets(target)}

    @server.tool()
    @guard_action
    def altium_read_project(path: str) -> dict:
        """Read project sheet references from a saved .PrjPcb without opening Altium."""
        target = Path(path).resolve()
        if not target.is_file() or target.suffix.lower() != '.prjpcb':
            raise ValueError('An existing .PrjPcb path is required')
        raw = target.read_bytes()
        encoding = 'utf-16' if raw.startswith((b'\xff\xfe',b'\xfe\xff')) else 'utf-8-sig'
        try:
            text = raw.decode(encoding)
        except UnicodeDecodeError:
            text = raw.decode('cp1251')
        project = configparser.ConfigParser(interpolation=None,strict=False)
        project.read_string(text)
        sheets = []
        for section in project.sections():
            if not section.lower().startswith('document'):
                continue
            document = project.get(section,'DocumentPath',fallback='').strip()
            if document.lower().endswith('.schdoc'):
                sheet = (target.parent / document.replace('\\','/')).resolve()
                if str(sheet) not in sheets:
                    sheets.append(str(sheet))
        return {'path': str(target), 'sheets': sheets, 'source':'saved_project_document_entries',
                'missing_sheets':[sheet for sheet in sheets if not Path(sheet).is_file()]}

    @server.tool()
    def altium_diagnose_job(job_dir: str) -> dict:
        """Read exact failed-job artifacts and editor liveness without launching a script. Does not infer unsaved state or permit replay."""
        return diagnose_job(job_dir)

    @server.tool()
    async def altium_recover_executor() -> dict:
        """After the failed interpreter has been stopped, run a bounded read-only health probe and clear the circuit breaker only on success. Does not stop/restart Altium or replay writes."""
        return await asyncio.to_thread(recover_executor)

    @server.tool()
    async def altium_prepare_component_package(mpn: str, manufacturer: str, source_url: str, downloaded_path: str) -> dict:
        """Preserve an already downloaded CAD file/archive under libraries/MPN/original and copy its contents to new. Refuses overwrites and non-CAD downloads. Returns unverified import status."""
        from component_package import prepare
        return await asyncio.to_thread(guard_action(prepare), mpn, manufacturer, source_url, downloaded_path)

    @server.tool()
    async def altium_download_component_package(mpn: str, manufacturer: str, url: str) -> dict:
        """Download a known public HTTPS CAD URL, preserve original and prepare new in the main engineering checkout. This does not search MPS, handle authentication, or verify electrical suitability."""
        from component_package import download_and_prepare
        return await asyncio.to_thread(guard_action(download_and_prepare), mpn, manufacturer, url)

    @server.tool()
    def altium_verify_component_original(package_path: str) -> dict:
        """Compare every original file against import-time SHA256 values without opening Altium."""
        from component_package import verify_original
        return verify_original(package_path)

    @server.tool()
    async def altium_compile_project(path: str) -> dict:
        """Compile exactly this project and return Altium's actual pin-net connectivity, compile boolean and Messages. success refers to API execution; compiled=False indicates unresolved compiler/ERC issues."""
        return await asyncio.to_thread(compile_project, path)

    @server.tool()
    async def altium_status(live: bool = False) -> dict:
        """Report installation and optional real round-trip to the open Altium editor."""
        return await asyncio.to_thread(status, live)

    @server.tool()
    async def altium_open_document(path: str) -> dict:
        """Open a specified existing Altium document through its native API."""
        return await asyncio.to_thread(open_document, path)

    @server.tool()
    async def altium_inspect_schematic(path: str) -> dict:
        """Read real components, pins, wires and labels from an explicitly targeted sheet."""
        return await asyncio.to_thread(inspect_schematic, path)

    @server.tool()
    async def altium_create_schematic(manifest_path: str, output_path: str) -> dict:
        """Create and save native components and wires from a reviewed pin-net manifest."""
        return await asyncio.to_thread(create_schematic, manifest_path, output_path)

    @server.tool()
    async def altium_set_component_parameter(path: str, designator: str, parameter: str, value: str) -> dict:
        """Back up the disk document, update one component parameter, and save via Altium."""
        return await asyncio.to_thread(set_component_parameter, path, designator, parameter, value)

    @server.tool()
    async def altium_run_delphiscript(body: str, declarations: str = "", helpers: str = "", timeout: int = 45) -> dict:
        """Execute native CAD API statements with an isolated job, step log and timeout. No GUI/shell automation."""
        return await asyncio.to_thread(run_script, body, declarations, helpers, timeout)

    @server.tool()
    async def altium_inspect_library_component(path: str, component: str) -> dict:
        """Select the exact LibReference in this SchLib through native API and read all parts/pins/fonts, including unsaved edits; no disk reload."""
        from library_api import inspect_library
        return await asyncio.to_thread(inspect_library, sys.modules[__name__], path, component)

    @server.tool()
    async def altium_format_library_pins(path: str, component: str, length_mm: float = 5.0, font_name: str = "GOST Common", font_size: int = 10) -> dict:
        """Set every pin's length in mm and Name/Designator font in pt across all parts. Selects exact LibReference, backs up disk and unsaved editor checkpoint, saves/reopens, verifies identity/geometry/types/models. Applies regular font."""
        from library_api import format_pins
        return await asyncio.to_thread(format_pins, sys.modules[__name__], path, component, length_mm, font_name, font_size)

    @server.tool()
    async def altium_repartition_library_component(path: str, component: str, manifest_path: str, replace_body: bool = False) -> dict:
        """Move every existing pin into specified parts/positions using an absolute JSON manifest; preserve identity/types/length/fonts/models. Requires complete unique designator/name map. Optional replace_body explicitly replaces all rectangles/free labels, preserving parameters. Backup/save/reload verification included; no PDF pin guesses."""
        from library_api import repartition
        return await asyncio.to_thread(repartition, sys.modules[__name__], path, component, manifest_path, replace_body)

    server.run(transport="stdio")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("action", choices=["serve", "status", "inspect", "open", "create", "parameter", "run", "compile", "library-inspect", "library-format", "library-repartition", "diagnose-job", "recover-executor", "prepare-component", "download-component", "verify-original"])
    parser.add_argument('--mpn')
    parser.add_argument('--manufacturer')
    parser.add_argument('--url')
    parser.add_argument("--live", action="store_true")
    parser.add_argument("--path")
    parser.add_argument("--manifest")
    parser.add_argument("--designator")
    parser.add_argument("--parameter")
    parser.add_argument("--value")
    parser.add_argument("--component")
    parser.add_argument("--length-mm", type=float, default=5.0)
    parser.add_argument("--font-name", default="GOST Common")
    parser.add_argument("--font-size", type=int, default=10)
    parser.add_argument("--replace-body", action="store_true")
    args = parser.parse_args()
    if args.action == "serve":
        serve()
        return
    from library_api import inspect_library, format_pins, repartition
    from component_package import prepare, download_and_prepare, verify_original
    actions = {
        "status": lambda: status(args.live),
        "diagnose-job": lambda: diagnose_job(args.path),
        "recover-executor": recover_executor,
        "prepare-component": lambda: prepare(args.mpn, args.manufacturer, args.url, args.path),
        "download-component": lambda: download_and_prepare(args.mpn, args.manufacturer, args.url),
        "verify-original": lambda: verify_original(args.path),
        "inspect": lambda: inspect_schematic(args.path),
        "open": lambda: open_document(args.path),
        "create": lambda: create_schematic(args.manifest, args.path),
        "parameter": lambda: set_component_parameter(args.path, args.designator, args.parameter, args.value),
        "run": lambda: run_script(**json.loads(Path(args.path).read_text(encoding="utf-8"))),
        "compile": lambda: compile_project(args.path),
        "library-inspect": lambda: inspect_library(sys.modules[__name__], args.path, args.component),
        "library-format": lambda: format_pins(sys.modules[__name__], args.path, args.component, args.length_mm, args.font_name, args.font_size),
        "library-repartition": lambda: repartition(sys.modules[__name__], args.path, args.component, args.manifest, args.replace_body),
    }
    print(json.dumps(guard_action(actions[args.action])(), ensure_ascii=True, indent=2))


if __name__ == "__main__":
    main()
