// Generated by Codex Altium bridge. All coordinates are in mils.
var JobLog: TStringList;
procedure LogStep(S: String);
begin
  JobLog.Add(S);
  JobLog.SaveToFile('C:\Users\makarlistkov\Documents\Work\Engineering\FPGA-COURSE-WORK\tools\altium\runtime\jobs\0b5f9f78b4034984a80b45aaa67e5ac6\steps.txt');
end;

procedure Run;
var
  ResultText: String;
  OutputLines: TStringList;
  SD: IServerDocument; L: ISch_Lib; C,LC: ISch_Component; I,LI: ISch_Iterator; P: ISch_Pin; N, Sz, Rot: Integer; U,It,B,S: Boolean; FN: WideString;
begin
  JobLog := TStringList.Create;
  ResultText := '';
  LogStep('START');
  try
    
SD := Client.GetDocumentByPath('C:\Users\makarlistkov\Documents\Work\Engineering\FPGA-COURSE-WORK\ARTIX\ARTIX\libraries\W25Q128JV\new\W25Q128JVSIQ.SchLib');
if SD <> Nil then begin
  
  L := Nil; if SD <> Nil then L := SchServer.GetSchDocumentByPath('C:\Users\makarlistkov\Documents\Work\Engineering\FPGA-COURSE-WORK\ARTIX\ARTIX\libraries\W25Q128JV\new\W25Q128JVSIQ.SchLib');
  if L <> Nil then begin
    C := Nil; LI := L.SchLibIterator_Create;
    LI.AddFilter_ObjectSet(MkSet(eSchComponent)); LC := LI.FirstSchObject;
    while LC <> Nil do begin if LC.LibReference = 'W25Q128JVSIQ' then C := LC; LC := LI.NextSchObject; end;
    L.SchIterator_Destroy(LI);
    if C <> Nil then begin
      LogStep('select exact library component');
      if L.CurrentSchComponent.LibReference <> 'W25Q128JVSIQ' then L.CurrentSchComponent := C;
      C := L.CurrentSchComponent;
      if C.LibReference = 'W25Q128JVSIQ' then begin
        
LogStep('documented Winbond Rev M source defect correction');
SchServer.ProcessControl.PreProcess(L,'');
try
I:=C.SchIterator_Create; I.AddFilter_ObjectSet(MkSet(ePin)); P:=I.FirstSchObject; N:=0;
while P<>Nil do begin
 if (P.Designator='1') or (P.Designator='6') then P.Electrical:=eInput
 else if (P.Designator='2') or (P.Designator='3') or (P.Designator='5') or (P.Designator='7') then P.Electrical:=eIO
 else if (P.Designator='4') or (P.Designator='8') then P.Electrical:=ePower;
 if P.Designator='7' then P.Name:='IO3';
 N:=N+1; P:=I.NextSchObject;
end; C.SchIterator_Destroy(I);
finally SchServer.ProcessControl.PostProcess(L,'Correct verified Flash source defect'); end;
SD.SetModified(True); L.GraphicallyInvalidate;
if N=8 then begin if SD.DoFileSave('') then ResultText:='{"saved":true,"source_defects_corrected":true}' else ResultText:='{"error":"SAVE_FAILED"}'; end else ResultText:='{"error":"PIN_COUNT_MISMATCH"}';

      end else ResultText := '{"error":"WRONG_ACTIVE_COMPONENT"}';
    end else ResultText := '{"error":"COMPONENT_NOT_FOUND"}';
  end else ResultText := '{"error":"NO_LIBRARY"}';
end else ResultText := '{"error":"DOCUMENT_NOT_OPEN"}';

    LogStep('FINISHED');
    OutputLines := TStringList.Create;
    OutputLines.Text := ResultText;
    OutputLines.SaveToFile('C:\Users\makarlistkov\Documents\Work\Engineering\FPGA-COURSE-WORK\tools\altium\runtime\jobs\0b5f9f78b4034984a80b45aaa67e5ac6\result.txt');
    OutputLines.Free;
  finally
    JobLog.Free;
  end;
end;
